/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Glossier({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/glossier.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Path.geometry} material={materials.Bastille} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glossier.gltf')
