/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3Dee (https://sketchfab.com/mellydeeis)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/retro-polaroid-camera-beta2-f42a67496c5047f99778817da83125dc
title: Retro Polaroid Camera (Beta2)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Polaroid({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/polaroid.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={1.3}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.31, 0.2, 0.52]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Material-material'].geometry} material={nodes['Material-material'].material} />
        </group>
        <group position={[-1.08, 0.05, 0.63]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['flash__material_glass_1-material'].geometry} material={materials.flash} />
        </group>
        <group position={[0.01, 0.66, -0.82]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Material_001-material'].geometry} material={materials['Material.001']} />
        </group>
        <group position={[1.11, 0.01, 0.79]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes['Glass_Lens_2Material_001-material'].geometry}
            material={nodes['Glass_Lens_2Material_001-material'].material}
          />
        </group>
        <group position={[0.09, -0.05, 0.53]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Glass_Lens_2Material_000-material'].geometry} material={materials.Glass_0} />
        </group>
        <group position={[-1.21, 0.02, -0.24]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.64]}>
          <mesh geometry={nodes['plastic_round_Lens_3Material_002-material'].geometry} material={materials.plastic_0} />
        </group>
        <group position={[-0.62, 0.05, 0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[0.85, 0.85, 2]}>
          <mesh
            geometry={nodes['Glass_Lens_2Material_001-material_1'].geometry}
            material={nodes['Glass_Lens_2Material_001-material_1'].material}
          />
        </group>
        <group position={[0.1, -0.05, -0.9]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Material_002-material'].geometry} material={materials['Material.002']} />
        </group>
        <group position={[0.21, 1.21, 0.38]} rotation={[Math.PI / 2, 0, 0]} scale={[1.06, 1, 1.06]}>
          <mesh geometry={nodes['Material-material_1'].geometry} material={nodes['Material-material_1'].material} />
        </group>
        <group position={[0.18, 0.69, -0.56]} rotation={[-Math.PI / 2, 0, -0.35]} scale={[0.82, 0.84, 1.64]}>
          <mesh geometry={nodes['plastic_round_Lens_3Material_001-material'].geometry} material={materials.plastic} />
        </group>
        <group position={[0.02, 0.88, -0.85]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['Material_003-material'].geometry} material={materials['Material.003']} />
        </group>
        <group position={[-1.27, 0.66, 0.53]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.47]}>
          <mesh
            geometry={nodes['YellowButtonMaterial53-material'].geometry}
            material={materials.YellowButtonMaterial53}
          />
        </group>
        <group position={[1.11, 1.53, 0.83]} rotation={[Math.PI / 2, 0, 0]} scale={[4.38, 4.38, 8.16]}>
          <mesh geometry={nodes['vision1Material0233-material'].geometry} material={materials.vision1Material0233} />
        </group>
        <group position={[1.11, 1.81, 0.83]} rotation={[Math.PI / 2, 0, 0]} scale={[4.38, 4.38, 8.16]}>
          <mesh
            geometry={nodes['vision1Material0233_001-material'].geometry}
            material={materials['vision1Material0233.001']}
          />
        </group>
        <group position={[-1.27, 0.58, 0.87]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.47]}>
          <mesh geometry={nodes['redMaterial334-material'].geometry} material={materials.redMaterial334} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/polaroid.gltf')
